# Printing Arrays

In [2]:
# One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [8]:
import numpy as np

# 1-D Array

a=np.arange(6)

In [9]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
# 2-D Array
b=np.arange(12).reshape(4,3)

In [12]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
# 3-Array

c=np.arange(24).reshape(2,3,4)

In [15]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Basic Operations With Array

In [ ]:
#  Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [17]:
a=np.array([20,30,40,50])
print(a)

[20 30 40 50]


In [20]:
b=np.array([1,2,3,5])
print(b)

[1 2 3 5]


In [23]:
c=a-b
print(c)

[19 28 37 45]


In [24]:
b**2

array([ 1,  4,  9, 25], dtype=int32)

In [25]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [26]:
a<35

array([ True,  True, False, False])

In [27]:
A = np.array( [[1,1], [0,1]] )
B= np. array([[2,0],  [3,4]])  

In [28]:
print(A*B) # Element wise Product

[[2 0]
 [0 4]]


In [29]:
A@B # Matrix Product

array([[5, 4],
       [3, 4]])

In [30]:
A.dot(B)

array([[5, 4],
       [3, 4]])

# Generate Random Numbers using Python


In [ ]:
# The function random() is one of them, it generates a number between 0 and 1.
# But there are other like the functions randint(min,max) and randrange(max).
import random
x=random.random()

In [79]:
x

0.7140547017348822

In [84]:
# The randint() method to generates a whole number (integer). You can use randint(0,50) to generate a random number between 0 and 50
x = random.randint(0,50)
print(x)

23


In [90]:
# o generate random integers between 0 and 9, you can use the function randrange(min,max).
from random import randrange
print(randrange(1,5))

3


In [91]:
# List Of Random Numbers

mylist = []

for i in range(0,100):
    x = random.randint(1,10)
    mylist.append(x)

print(mylist)

[3, 10, 9, 8, 1, 7, 4, 7, 3, 10, 8, 6, 6, 2, 8, 9, 4, 3, 8, 2, 9, 7, 9, 6, 9, 7, 5, 5, 3, 8, 6, 2, 5, 1, 8, 6, 5, 9, 3, 5, 2, 10, 7, 10, 2, 6, 9, 3, 7, 1, 4, 10, 8, 2, 5, 4, 1, 10, 6, 10, 7, 3, 8, 3, 9, 10, 2, 8, 2, 1, 3, 5, 2, 6, 7, 6, 3, 1, 4, 9, 1, 8, 8, 8, 10, 1, 5, 3, 7, 6, 2, 7, 9, 3, 5, 2, 2, 9, 6, 7]


In [93]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
# Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.
a= np.random.rand(2,3)

In [113]:
a

array([[0.0073384 , 0.1881579 , 0.83165684],
       [0.60778831, 0.98433312, 0.62895592]])

In [114]:
a.sum()

3.2482304872206784

In [115]:
a.min()

0.0073383990780655495

In [116]:
a.max()

0.984333123011492

In [117]:
# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
# However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

b=np.arange(12).reshape(3,4)

In [118]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
#sum of Each Column
b.sum(axis=0)

array([ 6, 22, 38])

In [122]:
# Min of each Row
b.min(axis=1)

array([0, 4, 8])

In [126]:
# Cum Sum Along Each Row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

array([ 0,  5, 10])

# Universal Functions

In [130]:
# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.
B=np.arange(3)
B

array([0, 1, 2])

In [131]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [132]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])