# Numpy 

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:
<ul>
    
   <li> A powerful N-dimensional array object. </li>
    
   <li> Sophisticated (broadcasting) functions.</li>
   
   <li>Tools for integrating C/C++ and Fortran code.</li>
    
   <li>Useful linear algebra, Fourier transform, and random number capabilities.</li>
    
</ul>

### NumPy – A Replacement for MatLab

NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib
(plotting library). This combination is widely used as a replacement for MatLab, a popular
platform for technical computing. However, Python alternative to MatLab is now seen as a
more modern and complete programming language.
It is open source, which is an added advantage of NumPy.


The most important object defined in NumPy is an N-dimensional array type called ndarray.
It describes the collection of items of the same type. Items in the collection can be accessed
using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray
is an object of data-type object (called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one
of array scalar types. The following diagram shows a relationship between ndarray, data type
object (dtype) and array scalar type

In [1]:
import numpy as np 
import pandas as pd

# NUMPY − NDARRAY OBJECT 

The most important object defined in NumPy is an N-dimensional array type called ndarray.It describes the collection of items of the same type. Items in the collection can be accessed
using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray
is an object of data-type object (called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one
of array scalar types.

An instance of ndarray class can be constructed by different array creation routines described
later in the tutorial. The basic ndarray is created using an array function in NumPy as follows:


In [5]:
np.array

<function numpy.array>

It creates an ndarray from any object exposing array interface, or from any method that
returns an array.


In [7]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
# More than one dimension 
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [11]:
# minimum dimensions
a=np.array([1, 2, 3,4,5], ndmin=2)
print (a)

[[1 2 3 4 5]]


In [13]:
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


The ndarray object consists of contiguous one-dimensional segment of computer memory,
combined with an indexing scheme that maps each item to a location in the memory block.
The memory block holds the elements in a row-major order (C style) or a column-major order
(FORTRAN or MatLab style).

# NUMPY − DATA TYPES

NumPy supports a much greater variety of numerical types than Python does. 

NumPy numerical types are instances of dtype (data-type) objects, each having unique
characteristics. The dtypes are available as np.bool_, np.float32, etc.


# NUMPY − ARRAY ATTRIBUTES 

 we will discuss the various array attributes of NumPy.

### ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to
resize the array

In [14]:
a=np.array([[1,2,3],[4,5,6]])
print (a.shape)


(2, 3)


In [16]:
# Resize the array 
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
print(a.shape)

(3, 2)


In [19]:
# NumPy also provides a reshape function to resize an array.
a = np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


### ndarray.ndim
This array attribute returns the number of array dimensions.


In [27]:
# an array of evenly spaced numbers
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
# This is one dimensional array 
a.ndim

1

In [30]:
# Now Reshape it
b=a.reshape(2,4,3)
b
# b is having three dimension 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### numpy.itemsize

This array attribute returns the length of each element of array in bytes.

In [31]:
# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype=np.int8)
x.itemsize

1

In [32]:
# dtype of array is float32 (4 bytes)
x = np.array([1,2,3,4,5], dtype=np.float32)
x.itemsize

4

### numpy.flags
The ndarray object has the following attributes. Its current values are returned by this
function.


|flags            |   Properties                                        |
|-----------------|-----------------------------------------------------|
|C_CONTIGUOUS (C) | The data is in a single, C-style contiguous segment.|
|F_CONTIGUOUS (F) | The data is in a single, Fortran-style contiguous segment.|
|OWNDATA (O) | The array owns the memory it uses or borrows it from another object.|
|WRITEABLE (W) | The data area can be written to. Setting this to False locks the data,making it read-only.|
|ALIGNED (A) | The data and all elements are aligned appropriately for the hardware.|
|UPDATEIFCOPY (U)| This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array.| 


In [34]:
x = np.array([1,2,3,4,5])
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# NUMPY − ARRAY CREATION ROUTINES
A new ndarray object can be constructed by any of the following array creation routines or
using a low-level ndarray constructor

#### numpy.empty
It creates an uninitialized array of specified shape and dtype. It uses the following constructor:

In [38]:
#  The elements in an array show random values as they are not initialized.
x = np.empty([3,2], dtype=int)
x

array([[-983720464,        587],
       [         0,          0],
       [    131075,  201395201]])

### numpy.zeros
Returns a new array of specified size, filled with zeros.

In [40]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [41]:
x = np.zeros((5,), dtype=np.int)
x

array([0, 0, 0, 0, 0])

In [44]:
x = np.zeros((5,5), dtype=np.int )
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### numpy.ones
Returns a new array of specified size and type, filled with ones.


In [46]:
# array of five ones. Default dtype is float
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [48]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# NUMPY − ARRAY FROM EXISTING DATA

### numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. This
routine is useful for converting Python sequence into ndarray.

In [49]:
# convert list to ndarray
x = [1,2,3]
a = np.asarray(x)
a

array([1, 2, 3])

In [50]:
x = [1,2,3]
a = np.asarray(x, dtype=float)
a

array([1., 2., 3.])

In [51]:
# ndarray from tuple
x=(1,2,3,4,5)
a=np.asarray(x)
a

array([1, 2, 3, 4, 5])

In [53]:
# ndarray from list of tuples

x = [(1,2,3),(4,5)]
a = np.asarray(x)
a


array([(1, 2, 3), (4, 5)], dtype=object)

# NUMPY − ARRAY FROM NUMERICAL RANGES

### numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range.
The format of the function is as follows:

In [71]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [72]:
# dtype set
x = np.arange(5, dtype=float)
x

array([0., 1., 2., 3., 4.])

In [73]:
# Start And Stop  Parameters 
x = np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

### numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number
of evenly spaced values between the interval is specified. The usage of this function is as
follows:


In [74]:
x=np.linspace(2.0, 3.0, num=5, retstep=True)
x

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [2]:
# endpoint set to false 

x = np.linspace(10,20, 5, endpoint = False) 
x

array([10., 12., 14., 16., 18.])

### numpy.logspace

This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

In [3]:
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [5]:
# set base of log space to 2 

a = np.logspace(1,10,num = 10, base = 2) 
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])