# NumPy - Arithmetic Operations

Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules.

In [1]:
import numpy as np 

In [2]:
#  First Array 
a=np.arange(9, dtype = np.float_).reshape(3,3) 
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [3]:
# Second Array
b = np.array([10,10,10]) 
b

array([10, 10, 10])

In [4]:
# Adding the two arrays 
np.add(a,b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [5]:
# Subtract two Arrays
np.subtract(a,b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [6]:
# Multiply the two arrays:' 
np.multiply(a,b) 

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

In [7]:
# 'Divide the two arrays:' 
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

### numpy.reciprocal()
This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the result is always 0 because of the way in which Python handles integer division. For integer 0, an overflow warning is issued.

In [8]:
a = np.array([0.25, 1.33, 1, 0, 100]) 
a

array([  0.25,   1.33,   1.  ,   0.  , 100.  ])

In [9]:
# 'After applying reciprocal function:' 
np.reciprocal(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  


array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

In [10]:
b = np.array([100], dtype = int)
b

array([100])

In [11]:
np.reciprocal(b) 

array([0], dtype=int32)

### numpy.power()
This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [12]:
a = np.array([10,100,1000])
a

array([  10,  100, 1000])

In [13]:
np.power(a,2)

array([    100,   10000, 1000000], dtype=int32)

### numpy.mod()
This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result.

In [14]:
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print("First Array")
print(a)
print('\n')

print("second Array ")
print(b)
print('\n')

print("Applying Mode() Function")
print (np.mod(a,b))
print("\n")

print("Applying Remainder () Function")
print(np.remainder(a,b))



First Array
[10 20 30]


second Array 
[3 5 7]


Applying Mode() Function
[1 0 2]


Applying Remainder () Function
[1 0 2]


### The following functions are used to perform operations on array with complex numbers.
<ul>
    <li>numpy.real() − returns the real part of the complex data type argument.</li>
<li>numpy.imag() − returns the imaginary part of the complex data type argument.</li>
<li>numpy.conj() − returns the complex conjugate, which is obtained by changing the sign of the imaginary part.</li>
<li>numpy.angle() − returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.</li>
  </ul>  

In [15]:
a= np.array([-5.6j, 0.2j, 11. , 1+1j])
a

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+1.j ])

In [16]:
#'Applying real() function:' 
np.real(a)

array([-0.,  0., 11.,  1.])

In [17]:
## 'Applying imag() function:' 
np.imag(a)

array([-5.6,  0.2,  0. ,  1. ])

In [18]:
# 'Applying conj() function:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

In [19]:
# 'Applying angle() function:' 
np.angle(a) 

array([-1.57079633,  1.57079633,  0.        ,  0.78539816])

In [20]:
# 'Applying angle() function again (result in degrees)' 
np.angle(a, deg = True)

array([-90.,  90.,   0.,  45.])

# NumPy - Statistical Functions

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc. from the given elements in the array. The functions are explained as follows −

### numpy.amin() and numpy.amax()
These functions return the minimum and the maximum from the elements in the given array along the specified axis.

In [21]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [24]:
# Min Function 
np.amin(a,1)

array([3, 3, 2])

In [25]:
np.min(a,0)

array([2, 4, 3])

In [26]:
# Mmax Function 
np.amax(a) 

9

### numpy.ptp()
The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

In [27]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [28]:
np.ptp(a) 

7

In [29]:
np.ptp(a, axis = 1) 

array([4, 5, 7])

In [30]:
np.ptp(a, axis = 0) 

array([6, 3, 6])

### numpy.percentile()
Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall. The function numpy.percentile() takes the following arguments.

#### numpy.percentile(a, q, axis)
##### a ---> is input array
#####  q --> is the percentile to compute must between 0-100
#####  axis --> is the axis along which the percentile calculated 

In [32]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [33]:
#'Applying percentile() function:' 
np.percentile(a,50) 

50.0

In [34]:
# 'Applying percentile() function along axis 1:' 
np.percentile(a,50, axis = 1) 

array([40., 20., 60.])

In [35]:
# 'Applying percentile() function along axis 0:' 
np.percentile(a,50, axis = 0)

array([50., 40., 60.])

### numpy.median()
Median is defined as the value separating the higher half of a data sample from the lower half. The numpy.median() function is used as shown in the following program.

In [36]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [37]:
'Applying median() function:' 
np.median(a) 

65.0

In [38]:
# 'Applying median() function along axis 0:' 
np.median(a, axis = 0) 

array([50., 90., 60.])

In [39]:
# 'Applying median() function along axis 1:' 
np.median(a, axis = 1) 

array([65., 80., 60.])

### numpy.mean()
Arithmetic mean is the sum of elements along an axis divided by the number of elements. The numpy.mean() function returns the arithmetic mean of elements in the array. If the axis is mentioned, it is calculated along it.

In [40]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [41]:
# 'Applying mean() function:' 
np.mean(a)

3.6666666666666665

In [42]:
#'Applying mean() function along axis 0:' 
np.mean(a, axis = 0) 

array([2.66666667, 3.66666667, 4.66666667])

In [43]:
#'Applying mean() function along axis 1:' 
np.mean(a, axis = 1)

array([2., 4., 5.])

### numpy.average()
Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by adding the product of the corresponding elements and dividing the sum by the sum of weights.

Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)

In [44]:
a = np.array([1,2,3,4]) 
a

array([1, 2, 3, 4])

In [45]:
# 'Applying average() function:' 
np.average(a) 

2.5

In [46]:
# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 
#'Applying average() function again:' 
np.average(a,weights = wts)

2.0

In [47]:
# Returns the sum of weights, if the returned parameter is set to True. 
print ('Sum of weights') 
np.average([1,2,3, 4],weights = [4,3,2,1], returned = True)

Sum of weights


(2.0, 10.0)

### Standard Deviation
Standard deviation is the square root of the average of squared deviations from mean. The formula for standard deviation is as follows −

std = sqrt(mean(abs(x - x.mean())**2))
If the array is [1, 2, 3, 4], then its mean is 2.5. Hence the squared deviations are [2.25, 0.25, 0.25, 2.25] and the square root of its mean divided by 4, i.e., sqrt (5/4) is 1.1180339887498949.

In [48]:
np.std([1,2,3,4])

1.118033988749895

### Variance
Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). In other words, the standard deviation is the square root of variance.

In [49]:
np.var([1,2,3,4])

1.25

# NumPy - Sort, Search & Counting Functions
A variety of sorting related functions are available in NumPy. These sorting functions implement different sorting algorithms, each of them characterized by the speed of execution, worst case performance, the workspace required and the stability of algorithms. Following table shows the comparison of three sorting algorithms.

|kind	|speed	|worst case	|work space	|stable
|--------|------|-----------|-----------|------|
|‘quicksort’|	1|	O(n^2)|	0	|no|
|‘mergesort’|	2|	O(n*log(n))|	~n/2|	yes|
| ‘heapsort’| 	3|	O(n*log(n))	|0	|no|

### numpy.sort()
The sort() function returns a sorted copy of the input array. It has the following parameters −

In [51]:
a = np.array([[3,7],[9,1]]) 
a

array([[3, 7],
       [9, 1]])

In [52]:
# 'Applying sort() function:' 
np.sort(a)

array([[3, 7],
       [1, 9]])

In [53]:
# ' Sort along axis 0:' 
np.sort(a, axis = 0) 

array([[3, 1],
       [9, 7]])

In [54]:
# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 
a

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [55]:
# 'Order by name:' 
np.sort(a, order = 'name')

array([(b'amar', 27), (b'anil', 25), (b'raju', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i4')])

### numpy.argsort()
The numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [56]:
x = np.array([3, 1, 2])
x

array([3, 1, 2])

In [58]:
y = np.argsort(x) 
x[y]

array([1, 2, 3])

In [59]:
# 'Reconstruct the original array using loop:' 
for i in y: 
    print (x[i])

1
2
3


### numpy.lexsort()
function performs an indirect sort using a sequence of keys. The keys can be seen as a column in a spreadsheet. The function returns an array of indices, using which the sorted data can be obtained. Note, that the last key happens to be the primary key of sort.

In [61]:
nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 
#'Applying lexsort() function:' 
ind

array([3, 1, 0, 2], dtype=int64)

In [62]:
# 'Use this index to get sorted data:' 
[nm[i] + ", " + dv[i] for i in ind] 

['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']

# NumPy - Matrix Library

NumPy package contains a Matrix library numpy.matlib. This module has functions that return matrices instead of ndarray objects.

matlib.empty()
The matlib.empty() function returns a new matrix without initializing the entries. The function takes the following parameters.

numpy.matlib.empty(shape, dtype, order)

In [63]:
import numpy.matlib
np.matlib.empty((2,2)) 
# filled with random data

matrix([[1., 2.],
        [3., 4.]])

### numpy.matlib.zeros()
This function returns the matrix filled with zeros.

In [64]:
np.matlib.zeros((2,2)) 

matrix([[0., 0.],
        [0., 0.]])

#### numpy.matlib.ones()
This function returns the matrix filled with 1s.

In [65]:
np.matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

### numpy.matlib.eye()
This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere. The function takes the following parameters.

numpy.matlib.eye(n, M,k, dtype)

In [66]:
np.matlib.eye(n = 3, M = 4, k = 0, dtype = float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

### numpy.matlib.identity()
The numpy.matlib.identity() function returns the Identity matrix of the given size. An identity matrix is a square matrix with all diagonal elements as 1.

In [67]:
 np.matlib.identity(5, dtype = float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])