# NumPy - Indexing & Slicing
Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [10]:
import numpy as np 

In [11]:
a = np.arange(10) 
s = slice(2,7,2) 
a[s]

array([2, 4, 6])

In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 7, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.

The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object

In [4]:
a = np.arange(10) 
b = a[2:7:2] 
b

array([2, 4, 6])

If only one parameter is put, a single item corresponding to the index will be returned. If a : is inserted in front of it, all items from that index onwards will be extracted. If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [12]:
import numpy as np 

a = np.arange(10) 
b = a[5] 
b

5

In [13]:
# slice items starting from index 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# slice items between indexes 
a[2:5]

array([2, 3, 4])

In [15]:
# For Multi -Dimensional Array 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]' )
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

In [16]:
# array to begin with 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

In [18]:
print ('Our array is:') 
print (a) 
 

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [19]:
# this returns array of items in the second column 
print ('The items in the second column are:' ) 
print (a[...,1] )


The items in the second column are:
[2 4 5]


In [20]:
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...] )

The items in the second row are:
[3 4 5]


In [21]:
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[...,1:])

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


# NumPy - Advanced Indexing
It is possible to make a selection from ndarray that is a non-tuple sequence, ndarray object of integer or Boolean data type, or a tuple with at least one item being a sequence object. Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

There are two types of advanced indexing − Integer and Boolean.
### Integer Indexing
This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.

In the following example, one element of specified column from each row of ndarray object is selected. Hence, the row index contains all row numbers, and the column index specifies the element to be selected.

In [23]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

In [24]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:' )
print (x)
print ('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:' )
y

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:


array([[ 0,  2],
       [ 9, 11]])

### Boolean Array Indexing
This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

In [25]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:' )
print (x)
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:' )
x[x > 5]

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:


array([ 6,  7,  8,  9, 10, 11])

# NumPy - Broadcasting
The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [26]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
c

array([ 10,  40,  90, 160])

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.
### Broadcasting is possible if the following rules are satisfied −
<ul>
    <li> Array with smaller ndim than the other is prepended with '1' in its shape.</li>
<li> Size in each dimension of the output shape is maximum of the input sizes in that dimension.</li>
<li> An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.</li>
<li> If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.</li>
</ul>

### A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true 

<ul>
<li> Arrays have exactly the same shape.</li>
<li>Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.</li>
<li>Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.</li>   
    </ul>

In [28]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a)
print ('\n')  
   
print ('Second array:')
print (b) 
print ('\n')  
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# NumPy - Iterating Over Array
NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer.

In [29]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
    print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

In [30]:
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:' )
b = a.T 
print (b)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
    print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
